#!/bin/bash
#
# A simple project to reduce the pain of getting (more than one & mostly interesting) stuff 
# from the internet by eliminating the need of URLs as much as possible.
# By stuff here, we mean the content which has been shared under Creative Commons License or as free.
# 
# Project : Rock-Yourself
# Code by : Afaque "AKI" Hussain
# Contact : Afaque.Hussain@outlook.com
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# Please read the GNU General Public License at <http://www.gnu.org/licenses/>.
#/


if [ -f "resultPage" ]; then 
  rm resultPage
fi 

if [ -f "videofile.part" ]; then 
  rm videofile.part
fi

prefix="http://www.youtube.com/results?search_query="

if [ -n "$1" ]; then
    filename=`echo $1 | sed 's/+/_/g'`
    wget --quiet -O resultPage $prefix$1
    isEmpty=`cat resultPage`

    if [ -n "$isEmpty" ]; then
        resource_url=`sed -n "/id=\"search-results\"/,/<\/span>/p" resultPage | grep -io 'href.*" c' | grep -o '".*"' | sed 's/"/"www.youtube.com/'| sed 's/"//g'`
        echo ""
        echo "Downloading $filename video from the internet .... "
        youtube-dl -o videofile $resource_url

        if [ -f "videofile" ]; then
            mv videofile $filename.mp4
            echo ""
            echo "$filename video downloaded successfully."
        else 
            echo ""
            echo "Check you entry mate! May be Youtube got confused about $filename."
        fi
 
        rm resultPage
    
    else
      echo ""
      echo "Well, this software kinda gets stuff from the Internet. Make sure you're connected to it. Cheers!"
    fi
else 
	echo "Cant get something from nothing!"
fi
