#!/bin/bash
# Brought to you by AKI.

has_wget=`which wget`
if [ -z "$has_wget" ]; then 
  echo ""
  echo "You don't seem to have wget. Installing now ... "
  sudo apt-get install wget
fi

has_youtube_dl=`which youtube-dl`
if [ -z "$has_youtube_dl" ]; then 
  echo ""
  echo "You don't seem to have youtube-dl. Installing now ... "
  sudo apt-get install youtube-dl
fi

has_ffmpeg=`which ffmpeg`
if [ -z "$has_ffmpeg" ]; then 
  echo ""
  echo "You don't seem to have ffmpeg. Installing now ... "
  sudo apt-get install ffmpeg
fi

if [ -f "resultPage" ]; then 
  rm resultPage
fi 

if [ -f "videofile.part" ]; then 
  rm videofile.part
fi 


prefix="http://www.youtube.com/results?search_query="
suffix="+lyrics"

is_songslist_empty=`cat $1 | wc -l`
if [ $is_songslist_empty -eq 0 ]; then
  echo ""
  echo "Ok now we've got a problem here! Following cases might be causing this:"
  echo "1. Either the file containing list of enteries does not exist or the path that you passed is not correct."
  echo "2. You have not written anything in your songslist or you have written just one line and have not pressed Enter before saving. \n In either case, write a line or more and make sure you have file containing the list of enteries end with an empty line."
echo "Different software, Different rules! What can we do?"
echo ""

else 
  while read line; do
    if [ -n "$line" ]; then
      search_query=`echo $line | sed 's/ /+/g'`
      wget --quiet -O resultPage $prefix$search_query$suffix
      isEmpty=`cat resultPage`

      if [ -n "$isEmpty" ]; then
        resource_url=`sed -n "/id=\"search-results\"/,/<\/span>/p" resultPage | grep -io 'href.*" c' | grep -o '".*"' | sed 's/"/"www.youtube.com/'| sed 's/"//g'`
        echo ""
        echo "Downloading $line stuff from the internet .... "
        youtube-dl -o videofile $resource_url

        if [ -f "videofile" ]; then
          echo ""
          echo "Stuff related to $line Downloaded. How about we add a little processing to it?"
          filename=`echo $line | sed 's/ /_/g'`
          ffmpeg -v 0 -i videofile -f mp3 -ab 192000 -vn $filename.mp3

          if [ -f "$filename.mp3" ]; then
            echo ""
            echo "Got $line stuff successfully, maybe :P" 
          else
            echo ""
            echo "Oops, something happened during processing. Probably the downloaded stuff was bad."
          fi 
          rm resultPage videofile
        else 
          echo ""
          echo "Check you SongsList Mate! May be Youtube got confused about $line."
          rm resultPage
        fi 
    
      else
        echo ""
        echo "Well, this software kinda gets stuff from the Internet. Make sure you're connected to it. Cheers!"
      fi     
    fi
  done < $1 
fi
